replicaCount: 1

image: morozovav82/users:2.0

service:
  type: NodePort
  port: 9000

appBasePath: '/users/'
  
postgresql:
  enabled: true
  postgresqlDatabase: users
  postgresqlUsername: users
  postgresqlPassword: qwerty123
  service:
    port: "5432"

ingress:
  enabled: true
  hosts:
    - host: arch.homework
      paths: ["/users"]
      
metrics:
  serviceMonitor:
    enabled: false