replicaCount: 1

image: morozovav82/users:2.0

service:
  type: NodePort
  port: 9000

appBasePath: '/users/'
authSigninUrl: 'http://$host/auth/signin'
authAuthUrl: 'http://auth-auth-chart.morozovav.svc.cluster.local:9010/auth'
  
postgresql:
  enabled: true
  postgresqlDatabase: users
  postgresqlUsername: users
  postgresqlPassword: qwerty123
  service:
    port: "5432"

ingress:
  enabled: true
  hosts:
    - host: arch.homework
      paths: ["/users"]
      
metrics:
  serviceMonitor:
    enabled: false