replicaCount: 2

image: morozovav82/users:1.5

service:
  type: NodePort
  port: 9000

appBasePath: '/users'
billUrl: 'http://bill-bill-chart.morozovav.svc.cluster.local:9000'
  
postgresql:
  enabled: true
  postgresqlDatabase: users
  postgresqlUsername: users
  postgresqlPassword: qwerty123
  postgresqlMaxConnections: 500
  postgresqlDbUserConnectionLimit: 500
  service:
    port: "5432"

ingress:
  enabled: true
  hosts:
    - host: arch.homework
      paths: ["/users"]
      
metrics:
  serviceMonitor:
    enabled: false