replicaCount: 1

image: morozovav82/users:1.6

service:
  type: NodePort
  port: 9000

appBasePath: '/users'

postgresql:
  enabled: false
  fullname: postgresql.morozovav.svc.cluster.local
  postgresqlDatabase: users
  postgresqlUsername: users
  postgresqlPassword: qwerty123
  postgresqlMaxConnections: 500
  postgresqlDbUserConnectionLimit: 500
  service:
    port: "5432"

mq:
  url: mq-rabbitmq.morozovav.svc.cluster.local
  port: 5672
  username: rabbit
  password: rabbit

ingress:
  enabled: true
  hosts:
    - host: arch.homework
      paths: ["/users"]
      
metrics:
  serviceMonitor:
    enabled: false