spring:
    datasource:
      driver-class-name: 'org.postgresql.Driver'
      url: jdbc:postgresql://localhost:5432/postgres?currentShema=users
      username: users
      password: qwerty123

app.basePath: /

#logging:
#  level:
#    root: debug
