spring:
    datasource:
      driver-class-name: 'org.postgresql.Driver'
      url: ${DB_URL}
      username: ${DB_USER}
      password: ${DB_PSW}

app.basePath:

#настройка actuator
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always