spring:
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.web.servlet.error.ErrorMvcAutoConfiguration # отключение стандартного переброса на страницу /error в случае ошибок
  datasource:
    driver-class-name: 'org.postgresql.Driver'
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PSW}
  rabbitmq:
    host: ${MQ_URL}
    port: ${MQ_PORT}
    username: ${MQ_USER}
    password: ${MQ_PSW}
  redis:
    host: ${REDIS_HOST}
    port: ${REDIS_PORT}

app.basePath:

active-mq:
  UserRegistered-exchange: UserRegisteredExchange

#настройка actuator
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always

---
#настройка для prometheus
management:
  metrics:
    distribution:
      percentiles[http.server.requests]: 0.5, 0.95, 0.99, 1
      percentiles-histogram[http.server.requests]: true