apiVersion: v1
kind: ConfigMap
metadata:
  name: users-config
data:
  BASE_APP_URL: '/otusapp/morozovav/'
  DATABASE_URL: 'jdbc:postgresql://192.168.212.37:5432/postgres?currentShema=users'
---
apiVersion: v1
kind: Secret
metadata:
  name: users-secret
type: Opaque
data:
  DATABASE_USER: dXNlcnM=
  DATABASE_PSW: cXdlcnR5MTIz
