apiVersion: apps/v1
kind: Deployment
metadata:
    name: users-deployment
spec:
    replicas: 2
    selector:
       matchLabels:
          app: users-app
    template:
       metadata:
          labels:
             app: users-app
       spec:
          containers:
          - name: users
            image: morozovav82/users:1.0
            ports:
              - name: web 
                containerPort: 8080
            env:
              - name: app_basePath
                valueFrom:
                  configMapKeyRef:
                    name: users-config
                    key: BASE_APP_URL
              - name: DB_URL
                valueFrom:
                  configMapKeyRef:
                    name: users-config
                    key: DATABASE_URL
              - name: DB_USER
                valueFrom:
                  secretKeyRef:
                    name: users-secret
                    key: DATABASE_USER
              - name: DB_PSW
                valueFrom:
                  secretKeyRef:
                    name: users-secret
                    key: DATABASE_PSW
                    
            livenessProbe:
              httpGet:
                port: 8080
                path: /actuator/health
              initialDelaySeconds: 10
              periodSeconds: 5
            readinessProbe:
              httpGet:
                port: 8080
                path: /actuator/health
              initialDelaySeconds: 10
              periodSeconds: 5